site_name: "GHGA Metadata Schema"
theme:
  name: material
  palette:
    scheme: default
    primary: teal

  font:
    text: Tilium Web
    code: Courier Prime
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: index.md
  - Schema Documentation: docs/index.md
  - Derived Schemas: derived-schemas.md
  - Contributing: contributing.md
  - LinkML Quickstart Guide: linkml-quickstart.md
  - Curating: curating.md
  - Maintaining: maintaining.md
  - Release Process: release-process.md
  - Versioning: versioning.md
  - Style Guide: style-guide.md
  - Referencing Ontologies: referencing-ontologies.md
  - Testing: testing.md

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

repo_url: https://github.com/ghga-de/ghga-metadata-schema
repo_name: ghga-de/ghga-metadata-schema
